/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#321200",
        "inverse-on-surface": "#f3f0ef",
        "secondary-fixed-dim": "#ffb787",
        "outline-variant": "#e0c0af",
        "surface-container-highest": "#e4e2e1",
        "on-surface-variant": "#584235",
        "on-primary": "#ffffff",
        "secondary": "#964900",
        "inverse-primary": "#ffb68b",
        "on-primary-container": "#5c2800",
        "primary-fixed-dim": "#ffb68b",
        "outline": "#8c7263",
        "surface": "#fcf9f8",
        "tertiary": "#b72301",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe851f",
        "on-error": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "secondary-fixed": "#ffdcc7",
        "error": "#ba1a1a",
        "on-secondary-container": "#612d00",
        "error-container": "#ffdad6",
        "primary": "#994700",
        "background": "#fcf9f8",
        "on-tertiary-fixed": "#3d0600",
        "on-tertiary-fixed-variant": "#8c1800",
        "surface-variant": "#e4e2e1",
        "primary-fixed": "#ffdbc8",
        "on-background": "#1b1c1c",
        "surface-dim": "#dcd9d9",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb4a4",
        "on-secondary-fixed-variant": "#723600",
        "surface-container": "#f0eded",
        "tertiary-fixed": "#ffdad3",
        "on-secondary-fixed": "#311300",
        "primary-container": "#ff7a00",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#753400",
        "surface-container-high": "#eae7e7",
        "inverse-surface": "#303030",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-tertiary-container": "#6f1100",
        "tertiary-container": "#ff7759",
        "surface-tint": "#994700"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
